Config({
    'network-name': '  تونس نت  ',
    'service-number': '772131004',
    'popup-adv-time': 5,
    'popup-adv-img-type': true,
    'popup-adv-repeat-after': 120,
    'login-type': 'User',
    'login-chap': 0,
    'news-line': '        {بسم الله الرحمن الرحيم}( قل للمؤمنين يغضوا من أبصرهم ويحفظوا فروجهم ذلك ازكى لهم إن الله خبير بما يصنعون )صدق الله العضيم   ',
    'input-type': 'tel',
    'input-autocomplete': 'on',
    'speed-trychange': 3, //عدد مرات هلاح التغيير
    'speed-trychange-timeout': 3, // مدة فترة  حضر التغيير بالدقائق
    'input-rm-white-spaces': 0,
    'input-to-lower': 0,
    'input-to-upper': 0,
    'input-to-arabic-numbers': 1,
    'input-only-numbers': 0,
    'input-no-numbers': 0,
    'input-only-alphanumeric': 0,
    'input-to-tel-type-when': 0,
    'enable-hot-cookie': 1,
    'enable-hot-blocker': 1,
    'clear-router-cookie': 1,
    'clear-hot-cookie': 1,
    'block-time': 1,
    'try-count': 20,
    'warn-when': 10,
    'warn-message':
        'تحذير !! عدد محاولاتك الخاطئة اصبح {{tryCounter}} محاولات, عدد المحاولات المسموح بها هي {{tryCount}} محاولات فقط, عدد محاولاتك المتبقية {{restTryCount}} محاولات, سيتم حظرك لمدة {{blockTime}} دقائق اذا تجاوزت العدد المسموح للمحاولات',
    'price-button': true,
    'sell-point-button': true,
    'app-store-status-button': false,
    'show-date-field': false,
    'loan-button': true,
    'login-speeds-mode': true,
    'redirect-to-esterahah': '',
    'redirect-to-mobasher': '',
    'app-store-base-url': '',
    'app-store-base-url-ext': '',
    profiles: [
        {
            price: '100 ريال',
            time: '0 ساعات',
        },
        {
            price: '150 ريال',
            time: '0 ساعات',
        },
 {
            price: '200 ريال',
            time: '0 ساعات',
        },
        {
            price: '250 ريال',
            time: '0 ساعات',
        },
 {          		
            price: '300 ريال',		
		    time: '0 ساعات',
        },
        {
            price: '500 ريال',
            time: '0 ساعات',
        },
{   
            price: '150 ريال',
            time: 'مفتوح ',
        },
    ],
    'sell-points': [
        { name: 'البقالات الموجودة في اماكن التغطية   ' },
        { name: '  772131004 ' },
    ],
})
